{
 "title": "MeshCore Paket-Analyse",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hash", "query": "9ffae49de88ae79f" }
  ]
 },
 "panels": [
  {
   "title": "Payload Typ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  payload_type\r\nFROM mc_rx\r\nWHERE packet_payload_sha256 = '${hash}'\r\nLIMIT 1",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Sender",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  grp_txt_sender_name AS \"Sender\"\r\nFROM mc_rx\r\nWHERE packet_payload_sha256 = '${hash}'\r\nLIMIT 1",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Cannel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  coalesce(channel, 'kein Channel') AS \"Channel\"\r\nFROM mc_rx\r\nWHERE packet_payload_sha256 = '${hash}'\r\nLIMIT 1",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Region",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  region AS \"Region\"\r\nFROM mc_rx\r\nWHERE packet_payload_sha256 = '${hash}'\r\nLIMIT 1",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Nachricht",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  grp_txt_body AS \"Nachricht\"\r\nFROM mc_rx\r\nWHERE packet_payload_sha256 = '${hash}'\r\nLIMIT 1",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    ts AS \"Zeit\",\r\n    hop_count AS \"Hops\",\r\n    nodes AS \"Kompletter Pfad\"\r\nFROM mc_rx\r\nWHERE packet_payload_sha256 = '${hash}'\r\nORDER BY ts",
     "selectedFormat": 2
    }
   ]
  }
 ]
}